menu:
  About: /about/
  Posts: /
  Archives: /archives/

socials:
  github: cnicodeme
  twitter: cx42net
  linkedin: cyrilnicodeme
  email: mailto:contact@cnicodeme.com

# favicon:

#Put into /source
avatar: avatar.jpeg

feed: /atom.xml

disqus: true